---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lesediti/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public_html $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp bootstrap.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
