<form method="POST" action="/auteur/livres/nouveau" enctype="multipart/form-data" class="max-w-3xl space-y-6">
    <?= csrf_field() ?>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div class="sm:col-span-2"><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Titre *</label><input type="text" name="titre" required class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent"></div>
        <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Slug (auto si vide)</label><input type="text" name="slug" class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent"></div>
        <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Sous-titre</label><input type="text" name="sous_titre" class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent"></div>
        <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Catégorie</label><select name="category_id" class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent"><option value="">Choisir...</option><?php foreach ($categories as $c): ?><option value="<?= $c->id ?>"><?= e($c->nom) ?></option><?php endforeach; ?></select></div>
        <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Langue</label><select name="langue" class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent"><option value="fr">Français</option><option value="en">Anglais</option><option value="ln">Lingala</option><option value="sw">Swahili</option></select></div>
    </div>
    <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Description courte *</label><textarea name="description_courte" rows="2" maxlength="500" required class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent resize-none"></textarea></div>
    <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Description longue</label><textarea name="description_longue" rows="6" class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent resize-none"></textarea></div>
    <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Mots-clés (séparés par des virgules)</label><input type="text" name="mots_cles" class="w-full bg-surface border border-border rounded px-4 py-2.5 text-sm text-white outline-none focus:border-accent"></div>
    <div class="grid grid-cols-2 sm:grid-cols-3 gap-4">
        <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">ISBN</label><input type="text" name="isbn" class="w-full bg-surface border border-border rounded px-3 py-2 text-sm text-white outline-none focus:border-accent"></div>
        <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Nb pages</label><input type="number" name="nombre_pages" class="w-full bg-surface border border-border rounded px-3 py-2 text-sm text-white outline-none focus:border-accent"></div>
        <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-1">Prix USD *</label><input type="number" step="0.01" name="prix_unitaire_usd" value="9.99" required class="w-full bg-surface border border-border rounded px-3 py-2 text-sm text-white outline-none focus:border-accent"></div>
    </div>
    <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-2">Couverture (image)</label><input type="file" name="couverture" accept="image/jpeg,image/png,image/webp" class="text-sm text-text-muted file:mr-3 file:py-2 file:px-4 file:rounded file:border-0 file:bg-surface-2 file:text-white file:font-medium file:cursor-pointer hover:file:bg-accent/20"><p class="text-text-dim text-xs mt-1">JPEG/PNG/WebP, max 2 Mo, recommandé 600x900px</p></div>
    <div><label class="block text-xs text-text-dim uppercase tracking-wider mb-2">Manuscrit PDF *</label><input type="file" name="manuscrit" accept="application/pdf" required class="text-sm text-text-muted file:mr-3 file:py-2 file:px-4 file:rounded file:border-0 file:bg-surface-2 file:text-white file:font-medium file:cursor-pointer hover:file:bg-accent/20"><p class="text-text-dim text-xs mt-1">PDF uniquement, max 50 Mo</p></div>
    <label class="flex items-center gap-2 text-sm text-text-muted cursor-pointer"><input type="checkbox" name="accessible_abonnement" checked class="accent-accent"> Inclus dans l'abonnement</label>
    <div class="flex gap-3 pt-4"><button type="submit" class="btn-primary">Soumettre pour validation</button><a href="/auteur/livres" class="btn-secondary">Annuler</a></div>
</form>
